apiVersion: v1
kind: Service
metadata:
  labels:
    app: ece-mvp
  name: ece-mvp
  namespace: ece
spec:
  type: NodePort
  ports:
  - name: "ece-mvp-service"
    port: 5000
    targetPort: 80
    nodePort: 30000
  selector:
    app: ece-mvp
  
